# Generated by Django 4.0.6 on 2022-07-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_blog', '0003_remove_bloggers_email_remove_bloggers_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='post/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_post',
            field=models.TextField(),
        ),
    ]
