# Generated by Django 4.0.6 on 2022-07-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web_blog', '0008_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggers',
            name='author',
            field=models.ImageField(blank=True, upload_to='blogger/'),
        ),
    ]
