# Generated by Django 4.0.6 on 2022-07-25 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web_blog', '0009_alter_bloggers_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_blog.bloggers'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web_blog.post'),
        ),
    ]
